export const tryNowStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    minHeight: "calc(100vh - 90px)",
    padding: "20px",
  },
  contentBox: {
    display: "flex",
    gap: "20px",
    marginTop: "30px",
    width: "100%",
    maxWidth: "1400px",
    margin: "30px auto 0",
    height: "calc(100vh - 200px)",
    minHeight: "600px",
    maxHeight: "calc(100vh - 200px)",
    overflow: "hidden",
  },
  analyticsSection: {
    flex: "2",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#ffffff",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid #e0e0e0",
    minWidth: "0",
    overflowY: "auto",
    overflowX: "hidden",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.08)",
    position: "relative",
    height: "100%",
    maxHeight: "100%",
    minHeight: 0,
    WebkitOverflowScrolling: "touch",
    scrollBehavior: "smooth",
    overscrollBehavior: "contain",
    overscrollBehaviorY: "contain",
    "&::-webkit-scrollbar": {
      width: "8px",
    },
    "&::-webkit-scrollbar-track": {
      background: "#f1f1f1",
      borderRadius: "4px",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#888",
      borderRadius: "4px",
      "&:hover": {
        background: "#555",
      },
    },
  },
  listingsSection: {
    flex: "1",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#f0f0f0",
    borderRadius: "12px",
    padding: "20px",
    border: "2px solid #4facfe",
    minWidth: "0",
    overflow: "hidden",
    height: "100%",
    maxHeight: "100%",
    minHeight: 0,
  },
  scrollableContent: {
    flex: "1 1 0%",
    overflowY: "auto",
    overflowX: "hidden",
    marginTop: "20px",
    paddingRight: "10px",
    minHeight: 0,
    maxHeight: "100%",
    height: "100%",
    position: "relative",
    WebkitOverflowScrolling: "touch",
    scrollBehavior: "smooth",
    overscrollBehavior: "contain",
    overscrollBehaviorY: "contain",
    "&::-webkit-scrollbar": {
      width: "8px",
    },
    "&::-webkit-scrollbar-track": {
      background: "#f1f1f1",
      borderRadius: "4px",
    },
    "&::-webkit-scrollbar-thumb": {
      background: "#888",
      borderRadius: "4px",
      "&:hover": {
        background: "#555",
      },
    },
  },
  debugLabel: {
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: "700",
    textAlign: "center",
    padding: "10px",
    marginBottom: "10px",
    borderRadius: "8px",
  },
  debugText: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: "14px",
    textAlign: "center",
    color: "#666",
    marginBottom: "10px",
  },
  debugItem: {
    padding: "15px",
    marginBottom: "10px",
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    border: "1px solid #ddd",
    fontFamily: "'Montserrat', sans-serif",
  },
};
