export const searchBarStyles = {
  searchBarContainer: {
    display: "flex",
    padding: "30px",
    justifyContent: "center",
    alignItems: "center",
  },
  searchBar: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.6)",
    backdropFilter: "blur(15px)",
    WebkitBackdropFilter: "blur(15px)",
    borderRadius: "50px",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.15)",
    padding: "8px",
    maxWidth: "800px",
    height: "70px",
    overflow: "hidden",
    border: "1px solid rgba(255, 255, 255, 0.4)",
  },
  whereSection: {
    padding: "16px 24px",
    flex: "1 1 auto",
    width: "auto",
    minWidth: "220px",
    maxWidth: "300px",
    marginRight: "4px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    borderRadius: "10px",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  inputSection: {
    padding: "16px 20px",
    flex: "1 1 auto",
    width: "auto",
    minWidth: "220px",
    maxWidth: "300px",
    marginLeft: "4px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    borderRadius: "10px",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  divider: {
    width: "1px",
    height: "40px",
    backgroundColor: "#e0e0e0",
    margin: "0 4px",
    flexShrink: 0,
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#222222",
    marginBottom: "2px",
    fontFamily: "'Montserrat', sans-serif",
  },
  placeholder: {
    fontSize: "14px",
    color: "#717171",
    fontFamily: "'Montserrat', sans-serif",
  },
  searchButton: {
    backgroundColor: "#FF5A5F",
    borderRadius: "50%",
    width: "54px",
    height: "54px",
    minWidth: "54px",
    marginLeft: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      backgroundColor: "#e04a4f",
    },
    "&:disabled": {
      backgroundColor: "#cccccc",
      cursor: "not-allowed",
    },
  },
  select: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: "14px",
    color: "#222222",
    border: "none",
    outline: "none",
    "& .MuiSelect-select": {
      padding: "4px 24px 4px 0 !important",
      display: "flex",
      alignItems: "center",
    },
    "&:before": {
      borderBottom: "none !important",
    },
    "&:after": {
      borderBottom: "none !important",
    },
    "&:hover:not(.Mui-disabled):before": {
      borderBottom: "none !important",
    },
    "& .MuiSelect-icon": {
      color: "#717171",
      right: "0px",
    },
    "& fieldset": {
      border: "none !important",
    },
    "&:hover fieldset": {
      border: "none !important",
    },
    "&.Mui-focused fieldset": {
      border: "none !important",
    },
  },
};
