export const searchBarStyles = {
  searchBarContainer: {
    display: "flex",
    padding: "30px",
    justifyContent: "center",
    alignItems: "center",
  },
  searchBar: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: "50px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    padding: "8px",
    width: "100%",
    maxWidth: "800px",
    height: "70px",
  },
  whereSection: {
    padding: "16px 24px",
    flex: "2",
    minWidth: "200px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    cursor: "pointer",
    borderRadius: "50px 0 0 50px",
    "&:hover": {
      backgroundColor: "#f2f2f2",
      width: "100%",
      borderRadius: "50px",
    },
  },
  inputSection: {
    padding: "16px 20px",
    flex: "1",
    minWidth: "120px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#f2f2f2",
      borderRadius: "50px",
    },
  },
  divider: {
    width: "1px",
    height: "40px",
    backgroundColor: "#e0e0e0",
    margin: "0 8px",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#222222",
    marginBottom: "2px",
    fontFamily: "'Montserrat', sans-serif",
  },
  placeholder: {
    fontSize: "14px",
    color: "#717171",
    fontFamily: "'Montserrat', sans-serif",
  },
  searchButton: {
    backgroundColor: "#FF5A5F",
    borderRadius: "50%",
    width: "54px",
    height: "54px",
    minWidth: "54px",
    marginLeft: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "&:hover": {
      backgroundColor: "#e04a4f",
    },
  },
};
