export const landingPageStyles = {
  tagline: {
    fontWeight: "800",
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "2rem", md: "3rem", lg: "3.5rem" },
    lineHeight: 1.2,
    marginBottom: "1rem",
  },
  main: {
    padding: { xs: "30px 20px", md: "60px 40px", lg: "80px 60px" },
    margin: "10px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "85vh",
    textAlign: "center",
  },
  content: {
    textAlign: "center",
    maxWidth: "1000px",
    margin: "0 auto",
  },
  paragraph: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "14px", md: "16px", lg: "18px" },
    color: "var(--color-primary)",
    lineHeight: 1.7,
    marginBottom: "1rem",
  },
  subheading: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "18px", md: "20px", lg: "22px" },
    fontWeight: "700",
    color: "#FF5A5F",
    marginBottom: "0.5rem",
  },
  featuresBox: {
    backgroundColor: "#f8f9fa",
    borderRadius: "16px",
    padding: { xs: "20px", md: "30px", lg: "40px" },
    margin: "20px 0",
    textAlign: "left",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.05)",
  },
  featureItem: {
    display: "flex",
    alignItems: "flex-start",
    padding: "8px 0",
  },
  featureText: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "14px", md: "15px", lg: "16px" },
    color: "var(--color-primary)",
    lineHeight: 1.6,
    "& strong": {
      color: "#FF5A5F",
      fontWeight: "600",
    },
  },
  footerText: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "14px", md: "16px" },
    color: "var(--color-primary)",
    lineHeight: 1.7,
    fontStyle: "italic",
    marginTop: "1rem",
    opacity: 0.9,
  },
  button: {
    marginTop: "20px",
    fontSize: "16px",
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: "700",
    width: "180px",
    alignSelf: "center",
    padding: "12px 24px",
    gap: "4px",
    "& .MuiButton-endIcon": {
      marginLeft: "4px",
    },
  },
};
