export const landingPageStyles = {
  tagline: {
    fontWeight: "800",
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "2rem", md: "3rem", lg: "3.5rem" },
    lineHeight: 1.2,
    marginBottom: "1rem",
    color: "#ffffff",
    textShadow: "0 2px 10px rgba(0, 0, 0, 0.3)",
  },
  main: {
    position: "relative",
    padding: { xs: "30px 20px", md: "60px 40px", lg: "80px 60px" },
    margin: "0",
    marginBottom: "0",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "85vh",
    textAlign: "center",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundAttachment: "fixed",
    borderRadius: "0",
    overflow: "hidden",
    width: "100%",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      width: "50px",
      bottom: 0,
      background: "linear-gradient(to right, rgba(255, 255, 255, 0.4) 0%, rgba(255, 255, 255, 0.15) 40%, transparent 100%)",
      pointerEvents: "none",
      zIndex: 2,
    },
    "&::after": {
      content: '""',
      position: "absolute",
      top: 0,
      right: 0,
      width: "50px",
      bottom: 0,
      background: "linear-gradient(to left, rgba(255, 255, 255, 0.4) 0%, rgba(255, 255, 255, 0.15) 40%, transparent 100%)",
      pointerEvents: "none",
      zIndex: 2,
    },
  },
  backgroundOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    zIndex: 0,
    backdropFilter: "blur(0.5px)",
  },
  content: {
    textAlign: "center",
    maxWidth: "1000px",
    margin: "0 auto",
    position: "relative",
    zIndex: 3,
  },
  paragraph: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "14px", md: "16px", lg: "18px" },
    color: "#ffffff",
    lineHeight: 1.7,
    marginBottom: "1rem",
    textShadow: "0 1px 5px rgba(0, 0, 0, 0.3)",
  },
  subheading: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "18px", md: "20px", lg: "22px" },
    fontWeight: "700",
    color: "#FF5A5F",
    marginBottom: "0.5rem",
  },
  featuresBox: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    backdropFilter: "blur(10px)",
    borderRadius: "16px",
    padding: { xs: "20px", md: "30px", lg: "40px" },
    margin: "20px 0",
    textAlign: "left",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.2)",
    border: "1px solid rgba(255, 255, 255, 0.3)",
  },
  featureItem: {
    display: "flex",
    alignItems: "flex-start",
    padding: "8px 0",
  },
  featureText: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "14px", md: "15px", lg: "16px" },
    color: "var(--color-primary)",
    lineHeight: 1.6,
    "& strong": {
      color: "#FF5A5F",
      fontWeight: "600",
    },
  },
  footerText: {
    fontFamily: "'Montserrat', sans-serif",
    fontSize: { xs: "14px", md: "16px" },
    color: "#ffffff",
    lineHeight: 1.7,
    fontStyle: "italic",
    marginTop: "1rem",
    opacity: 0.95,
    textShadow: "0 1px 5px rgba(0, 0, 0, 0.3)",
  },
  button: {
    marginTop: "20px",
    fontSize: "16px",
    fontFamily: "'Montserrat', sans-serif",
    fontWeight: "700",
    width: "180px",
    alignSelf: "center",
    padding: "12px 24px",
    gap: "4px",
    "& .MuiButton-endIcon": {
      marginLeft: "4px",
    },
  },
};
